version: '3.8'
services:
  ubuntu-minimal:
    image: ubuntu:20.04
    container_name: ubuntu-minimal
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "2.0"
